var fixture = module.exports = {
  
twitter:  { twitter: 
             { token: '3trJcW9E43JAudvQeGthn82mDZvOtfbf99y1djNiS8',
               tokenSecret: 'L9YFqfmqOGSgBLkX7Q5mmwpRjDew8eRqgugPoNwbYE',
               verifier: 'rypAXiVCU2wzzBqIuL7nIVDegVQA9jOq3uBxVDTphc',
               user: 
                { profile_background_tile: true,
                  protected: false,
                  contributors_enabled: false,
                  url: 'http://blog.outsider.ne.kr',
                  name: 'Outsider',
                  id_str: '7932892',
                  default_profile_image: false,
                  profile_link_color: '009999',
                  default_profile: false,
                  utc_offset: 32400,
                  created_at: 'Fri Aug 03 14:33:57 +0000 2007',
                  friends_count: 630,
                  profile_sidebar_border_color: 'eeeeee',
                  is_translator: false,
                  following: true,
                  time_zone: 'Seoul',
                  profile_image_url: 'http://a3.twimg.com/profile_images/1084434666/outsider_type_normal.jpg',
                  description: 'Front-End & Server-Side Developer',
                  follow_request_sent: false,
                  profile_use_background_image: true,
                  favourites_count: 35,
                  show_all_inline_media: false,
                  verified: false,
                  geo_enabled: true,
                  profile_background_color: '131516',
                  screen_name: 'Outsideris',
                  profile_background_image_url: 'http://a1.twimg.com/images/themes/theme14/bg.gif',
                  id: 7932892,
                  listed_count: 83,
                  statuses_count: 15789,
                  notifications: false,
                  profile_background_image_url_https: 'https://si0.twimg.com/images/themes/theme14/bg.gif',
                  profile_text_color: '333333',
                  lang: 'en',
                  profile_sidebar_fill_color: 'efefef',
                  followers_count: 807,
                  profile_image_url_https: 'https://si0.twimg.com/profile_images/1084434666/outsider_type_normal.jpg',
                  location: 'South Korea' },
               accessToken: '7932892-X2tA5uXoUf24PgSFu4Cu7paTocI31VeNHXn77Z3w78',
               accessTokenSecret: 'eOGhpxXiPGRZw3drHfxx53gyyAff0mKvCdXgFK4' },
            loggedIn: true,
            userId: 7932892 }
}